import type { Clinica, Cita, DashboardStats } from "@/types"

export const CLINICAS_MOCK: Clinica[] = [
  {
    id: "1",
    nombre: "Sonrisa Perfecta Dental",
    slug: "sonrisa-perfecta-dental",
    descripcion: "Centro dental de vanguardia especializado en turismo medico. Atendemos pacientes de EE.UU. y Canada con tecnologia de punta y precios accesibles.",
    direccion: "Av. Revolucion 1234, Col. Centro",
    ciudad: "Tijuana",
    telefono: "+52 664 123 4567",
    email: "contacto@sonrisaperfecta.mx",
    sitioWeb: "https://sonrisaperfecta.mx",
    imagen: "https://images.unsplash.com/photo-1629909615184-74f495363b67?w=800&q=80",
    rating: 4.9,
    totalResenas: 347,
    idiomas: ["es", "en"],
    especialidades: ["ortodoncia", "implantes", "estetica", "general"],
    aseguradoras: ["blue_cross", "aetna", "cigna"],
    verificada: true,
    planSuscripcion: "premium",
    horario: {
      lunes: { abre: "08:00", cierra: "18:00" },
      martes: { abre: "08:00", cierra: "18:00" },
      miercoles: { abre: "08:00", cierra: "18:00" },
      jueves: { abre: "08:00", cierra: "18:00" },
      viernes: { abre: "08:00", cierra: "17:00" },
      sabado: { abre: "09:00", cierra: "14:00" },
    },
    coordenadas: { lat: 32.5149, lng: -117.0382 },
  },
  {
    id: "2",
    nombre: "BajaDent Clinic",
    slug: "bajadent-clinic",
    descripcion: "Especialistas en implantes y rehabilitacion oral. Mas de 15 anos sirviendo a pacientes internacionales con los mas altos estandares de calidad.",
    direccion: "Blvd. Agua Caliente 8900, Zona Rio",
    ciudad: "Tijuana",
    telefono: "+52 664 987 6543",
    email: "info@bajadent.com",
    imagen: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=800&q=80",
    rating: 4.8,
    totalResenas: 218,
    idiomas: ["es", "en"],
    especialidades: ["implantes", "endodoncia", "cirugia", "periodoncia"],
    aseguradoras: ["humana", "united_health", "medicare"],
    verificada: true,
    planSuscripcion: "profesional",
    horario: {
      lunes: { abre: "09:00", cierra: "19:00" },
      martes: { abre: "09:00", cierra: "19:00" },
      miercoles: { abre: "09:00", cierra: "19:00" },
      jueves: { abre: "09:00", cierra: "19:00" },
      viernes: { abre: "09:00", cierra: "18:00" },
    },
    coordenadas: { lat: 32.5209, lng: -117.0114 },
  },
  {
    id: "3",
    nombre: "Clinica Dental Smile Border",
    slug: "smile-border",
    descripcion: "Tu sonrisa es nuestro compromiso. Ofrecemos tratamientos de ortodoncia y estetica dental con tecnologia digital avanzada.",
    direccion: "Calle 5ta 456, Colonia Cacho",
    ciudad: "Tijuana",
    telefono: "+52 664 555 7890",
    email: "hola@smileborder.mx",
    imagen: "https://images.unsplash.com/photo-1588776814546-1ffbb9b01b4c?w=800&q=80",
    rating: 4.7,
    totalResenas: 156,
    idiomas: ["es", "en"],
    especialidades: ["ortodoncia", "estetica", "pediatrica"],
    aseguradoras: ["metlife", "cigna", "aetna"],
    verificada: true,
    planSuscripcion: "profesional",
    horario: {
      lunes: { abre: "08:30", cierra: "17:30" },
      martes: { abre: "08:30", cierra: "17:30" },
      miercoles: { abre: "08:30", cierra: "17:30" },
      jueves: { abre: "08:30", cierra: "17:30" },
      viernes: { abre: "08:30", cierra: "16:00" },
      sabado: { abre: "10:00", cierra: "13:00" },
    },
    coordenadas: { lat: 32.5278, lng: -117.0353 },
  },
  {
    id: "4",
    nombre: "Centro Odontologico del Noroeste",
    slug: "codo-noroeste",
    descripcion: "Mas de 20 anos de experiencia en odontologia general y especialidades. Personal certificado y ambiente familiar.",
    direccion: "Av. 16 de Septiembre 2100",
    ciudad: "Mexicali",
    telefono: "+52 686 100 2300",
    email: "citas@codonoroeste.mx",
    imagen: "https://images.unsplash.com/photo-1609840114035-3c981b782dfe?w=800&q=80",
    rating: 4.6,
    totalResenas: 89,
    idiomas: ["es"],
    especialidades: ["general", "endodoncia", "periodoncia"],
    aseguradoras: ["medicaid", "medicare"],
    verificada: false,
    planSuscripcion: "basico",
    horario: {
      lunes: { abre: "09:00", cierra: "17:00" },
      martes: { abre: "09:00", cierra: "17:00" },
      miercoles: { abre: "09:00", cierra: "17:00" },
      jueves: { abre: "09:00", cierra: "17:00" },
      viernes: { abre: "09:00", cierra: "15:00" },
    },
    coordenadas: { lat: 32.6245, lng: -115.4523 },
  },
  {
    id: "5",
    nombre: "Baja Smile Studio",
    slug: "baja-smile-studio",
    descripcion: "Estetica dental de alto nivel. Carillas, blanqueamiento y rehabilitacion completa para tu mejor sonrisa.",
    direccion: "Paseo Playas de Tijuana 789",
    ciudad: "Tijuana",
    telefono: "+52 664 333 9900",
    email: "studio@bajasmile.com",
    imagen: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=800&q=80",
    rating: 4.9,
    totalResenas: 412,
    idiomas: ["es", "en"],
    especialidades: ["estetica", "implantes", "ortodoncia"],
    aseguradoras: ["blue_cross", "cigna", "humana", "aetna"],
    verificada: true,
    planSuscripcion: "premium",
    horario: {
      lunes: { abre: "08:00", cierra: "20:00" },
      martes: { abre: "08:00", cierra: "20:00" },
      miercoles: { abre: "08:00", cierra: "20:00" },
      jueves: { abre: "08:00", cierra: "20:00" },
      viernes: { abre: "08:00", cierra: "18:00" },
      sabado: { abre: "09:00", cierra: "15:00" },
    },
    coordenadas: { lat: 32.4853, lng: -117.0602 },
  },
  {
    id: "6",
    nombre: "Dental Tecate Express",
    slug: "dental-tecate-express",
    descripcion: "Clinica moderna con atencion rapida y eficiente. Ideal para consultas de urgencia y tratamientos preventivos.",
    direccion: "Blvd. Juarez 300, Tecate",
    ciudad: "Tecate",
    telefono: "+52 665 654 3210",
    email: "contacto@dentaltecate.mx",
    imagen: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&q=80",
    rating: 4.4,
    totalResenas: 67,
    idiomas: ["es"],
    especialidades: ["general", "pediatrica"],
    aseguradoras: ["metlife"],
    verificada: false,
    planSuscripcion: "basico",
    horario: {
      lunes: { abre: "09:00", cierra: "18:00" },
      martes: { abre: "09:00", cierra: "18:00" },
      miercoles: { abre: "09:00", cierra: "18:00" },
      jueves: { abre: "09:00", cierra: "18:00" },
      viernes: { abre: "09:00", cierra: "16:00" },
    },
    coordenadas: { lat: 32.5685, lng: -116.6296 },
  },
]

// Doctores exportados para usarlos en filtros y formularios
export const DOCTORES_MOCK = [
  { id: "d1", nombre: "Dr. Carlos Mendoza", especialidad: "ortodoncia", avatar: "https://ui-avatars.com/api/?name=Carlos+Mendoza&background=0891B2&color=fff" },
  { id: "d2", nombre: "Dra. Andrea Vallejo", especialidad: "implantes", avatar: "https://ui-avatars.com/api/?name=Andrea+Vallejo&background=10B981&color=fff" },
  { id: "d3", nombre: "Dr. Roberto Flores", especialidad: "cirugia", avatar: "https://ui-avatars.com/api/?name=Roberto+Flores&background=6366F1&color=fff" },
  { id: "d4", nombre: "Dra. Lucia Reyes", especialidad: "estetica", avatar: "https://ui-avatars.com/api/?name=Lucia+Reyes&background=EC4899&color=fff" },
]

// Helper para fecha relativa al dia actual
function d(offsetDays: number, time: string): string {
  const date = new Date()
  date.setDate(date.getDate() + offsetDays)
  return date.toISOString().replace(/T.*/, `T${time}`)
}

export let CITAS_MOCK: Cita[] = [
  // HOY
  { id: "c1", pacienteId: "p1", pacienteNombre: "Sarah Johnson", pacienteAvatar: "https://ui-avatars.com/api/?name=Sarah+Johnson&background=0891B2&color=fff", clinicaId: "1", doctorId: "d1", doctorNombre: "Dr. Carlos Mendoza", fecha: d(0, "09:00:00"), duracionMinutos: 60, tratamiento: "ortodoncia", estado: "confirmada", notas: "Revision de brackets. Paciente de San Diego.", esTurismo: true },
  { id: "c2", pacienteId: "p2", pacienteNombre: "Mike Rodriguez", pacienteAvatar: "https://ui-avatars.com/api/?name=Mike+Rodriguez&background=10B981&color=fff", clinicaId: "1", doctorId: "d2", doctorNombre: "Dra. Andrea Vallejo", fecha: d(0, "10:30:00"), duracionMinutos: 90, tratamiento: "implantes", estado: "programada", notas: "Primera consulta de implante. Viene de Phoenix.", esTurismo: true },
  { id: "c3", pacienteId: "p3", pacienteNombre: "Emily Chen", pacienteAvatar: "https://ui-avatars.com/api/?name=Emily+Chen&background=6366F1&color=fff", clinicaId: "1", doctorId: "d1", doctorNombre: "Dr. Carlos Mendoza", fecha: d(0, "12:00:00"), duracionMinutos: 45, tratamiento: "estetica", estado: "en_curso", esTurismo: false },
  { id: "c4", pacienteId: "p4", pacienteNombre: "John Smith", pacienteAvatar: "https://ui-avatars.com/api/?name=John+Smith&background=F59E0B&color=fff", clinicaId: "1", doctorId: "d3", doctorNombre: "Dr. Roberto Flores", fecha: d(0, "14:00:00"), duracionMinutos: 120, tratamiento: "cirugia", estado: "programada", notas: "Extraccion de muela del juicio x2.", esTurismo: true },
  { id: "c5", pacienteId: "p5", pacienteNombre: "Maria Lopez", pacienteAvatar: "https://ui-avatars.com/api/?name=Maria+Lopez&background=EC4899&color=fff", clinicaId: "1", doctorId: "d2", doctorNombre: "Dra. Andrea Vallejo", fecha: d(0, "16:00:00"), duracionMinutos: 30, tratamiento: "general", estado: "confirmada", esTurismo: false },
  // MANANA
  { id: "c6", pacienteId: "p6", pacienteNombre: "Tom Garcia", pacienteAvatar: "https://ui-avatars.com/api/?name=Tom+Garcia&background=8B5CF6&color=fff", clinicaId: "1", doctorId: "d4", doctorNombre: "Dra. Lucia Reyes", fecha: d(1, "09:30:00"), duracionMinutos: 60, tratamiento: "estetica", estado: "confirmada", notas: "Blanqueamiento dental. Viene de Los Angeles.", esTurismo: true },
  { id: "c7", pacienteId: "p7", pacienteNombre: "Laura Martinez", pacienteAvatar: "https://ui-avatars.com/api/?name=Laura+Martinez&background=F97316&color=fff", clinicaId: "1", doctorId: "d1", doctorNombre: "Dr. Carlos Mendoza", fecha: d(1, "11:00:00"), duracionMinutos: 45, tratamiento: "ortodoncia", estado: "programada", esTurismo: false },
  { id: "c8", pacienteId: "p8", pacienteNombre: "Robert Kim", pacienteAvatar: "https://ui-avatars.com/api/?name=Robert+Kim&background=14B8A6&color=fff", clinicaId: "1", doctorId: "d3", doctorNombre: "Dr. Roberto Flores", fecha: d(1, "15:00:00"), duracionMinutos: 90, tratamiento: "cirugia", estado: "programada", notas: "Consulta pre-operatoria de implante.", esTurismo: true },
  // EN 2 DIAS
  { id: "c9", pacienteId: "p9", pacienteNombre: "Ana Gutierrez", pacienteAvatar: "https://ui-avatars.com/api/?name=Ana+Gutierrez&background=EF4444&color=fff", clinicaId: "1", doctorId: "d2", doctorNombre: "Dra. Andrea Vallejo", fecha: d(2, "10:00:00"), duracionMinutos: 60, tratamiento: "implantes", estado: "confirmada", esTurismo: false },
  { id: "c10", pacienteId: "p10", pacienteNombre: "Carlos White", pacienteAvatar: "https://ui-avatars.com/api/?name=Carlos+White&background=0891B2&color=fff", clinicaId: "1", doctorId: "d4", doctorNombre: "Dra. Lucia Reyes", fecha: d(2, "13:00:00"), duracionMinutos: 30, tratamiento: "estetica", estado: "programada", notas: "Carillas ceramicas - seguimiento.", esTurismo: false },
  // EN 3 DIAS
  { id: "c11", pacienteId: "p11", pacienteNombre: "Jessica Brown", pacienteAvatar: "https://ui-avatars.com/api/?name=Jessica+Brown&background=10B981&color=fff", clinicaId: "1", doctorId: "d1", doctorNombre: "Dr. Carlos Mendoza", fecha: d(3, "09:00:00"), duracionMinutos: 60, tratamiento: "ortodoncia", estado: "confirmada", esTurismo: true },
  { id: "c12", pacienteId: "p12", pacienteNombre: "David Lee", pacienteAvatar: "https://ui-avatars.com/api/?name=David+Lee&background=6366F1&color=fff", clinicaId: "1", doctorId: "d3", doctorNombre: "Dr. Roberto Flores", fecha: d(3, "14:30:00"), duracionMinutos: 120, tratamiento: "cirugia", estado: "programada", notas: "Extraccion multiple.", esTurismo: true },
  // HACE 2 DIAS (pasadas)
  { id: "c13", pacienteId: "p3", pacienteNombre: "Emily Chen", pacienteAvatar: "https://ui-avatars.com/api/?name=Emily+Chen&background=6366F1&color=fff", clinicaId: "1", doctorId: "d4", doctorNombre: "Dra. Lucia Reyes", fecha: d(-2, "10:00:00"), duracionMinutos: 45, tratamiento: "estetica", estado: "completada", esTurismo: false },
  { id: "c14", pacienteId: "p1", pacienteNombre: "Sarah Johnson", pacienteAvatar: "https://ui-avatars.com/api/?name=Sarah+Johnson&background=0891B2&color=fff", clinicaId: "1", doctorId: "d1", doctorNombre: "Dr. Carlos Mendoza", fecha: d(-2, "15:00:00"), duracionMinutos: 60, tratamiento: "ortodoncia", estado: "completada", esTurismo: true },
  // EN 5 DIAS
  { id: "c15", pacienteId: "p5", pacienteNombre: "Maria Lopez", pacienteAvatar: "https://ui-avatars.com/api/?name=Maria+Lopez&background=EC4899&color=fff", clinicaId: "1", doctorId: "d2", doctorNombre: "Dra. Andrea Vallejo", fecha: d(5, "11:00:00"), duracionMinutos: 30, tratamiento: "general", estado: "programada", esTurismo: false },
  { id: "c16", pacienteId: "p6", pacienteNombre: "Tom Garcia", pacienteAvatar: "https://ui-avatars.com/api/?name=Tom+Garcia&background=8B5CF6&color=fff", clinicaId: "1", doctorId: "d4", doctorNombre: "Dra. Lucia Reyes", fecha: d(5, "14:00:00"), duracionMinutos: 60, tratamiento: "estetica", estado: "confirmada", notas: "Seguimiento blanqueamiento.", esTurismo: true },
  // CANCELADA
  { id: "c17", pacienteId: "p7", pacienteNombre: "Laura Martinez", pacienteAvatar: "https://ui-avatars.com/api/?name=Laura+Martinez&background=F97316&color=fff", clinicaId: "1", doctorId: "d1", doctorNombre: "Dr. Carlos Mendoza", fecha: d(1, "16:00:00"), duracionMinutos: 45, tratamiento: "ortodoncia", estado: "cancelada", notas: "Paciente cancelo por viaje.", esTurismo: false },
]

export const DASHBOARD_STATS_MOCK: DashboardStats = {
  citasHoy: 8,
  pacientesActivos: 142,
  ingresosMes: 28450,
  mensajesNuevos: 5,
  citasSemana: 34,
  tasaOcupacion: 87,
}